# POVME 3.0 Sample Input File

GridSpacing            0.5                                 

InclusionSphere  48.950  57.333 212.874 5.0 #pointed 
#InclusionSphere  48.040  56.540 213.350 5.0  #interior 
#InclusionSphere 48.465  56.538 213.110 5.0 #barbed     
#InclusionSphere 48.550  52.840 212.920 5.0 #n111s interior 
#InclusionSphere 47.610  54.780 213.170 5.0 #JASP

# Load the PDB trajectory file
PDBFileName                 pointed_palign_proteinadpmg_unbiased12.pdb

# Tell POVME how to identify points that are within the binding pocket.
DistanceCutoff              1.09                           # Any point that comes within this
                                                           # distance of any receptor atom's van der
							   # Waals surface will not be considered
							   # part of the pocket volume. 1.09
							   # Angstroms was chosen as the default
							   # value because that is the van der Waals
							   # radius of a hydrogen atom.

ConvexHullExclusion         first                          # The convex hull is a method of
                                                           # determining where a pocket "ends" on
                                                           # the outside of the protein. Portions
                                                           # of the inclusion region which lie
                                                           # outside of the convex hull are removed.
                                                           # In previous versions, this would be
                                                           # recalculated for each individual frame,
                                                           # however this led to significant numerical
                                                           # noise as the motion of the protein in
                                                           # different frames could radically redefine
                                                           # the convex hull. A consistent convex hull
                                                           # can now be used in all frames by giving
                                                           # the "first" or "max" keywords
                                                           # here. "first" applied the convex hull from
                                                           # the first frame to all others."max" draws 
                                                           # a convex hull around all
                                                           # the frames superimposed simultaneously
                                                           # (and may take a while on large
                                                           # trajectories). To reproduce previous
                                                           # behavior, the "each" keyword may be used.
                                                           # Any other keyword will not use the convex
                                                           # hull exclusion method.



#SeedSphere  48.950  57.333 212.874 5.0 #Pointed 
#SeedSphere  48.040  56.540 213.350 5.0   # interior        
#SeedSphere 48.465  56.538 213.110 5.0 #barbed
#SeedSphere 48.550  52.840 212.920 5.0 #n111s interior
#SeedSphere 47.610  54.780 213.170 5.0 #JASP 


ContiguousPointsCriteria    3                              # Two pocket volumes are considered
                                                           # "contiguous" if they share at least
							   # this number neighboring points in
							   # common. Note that points that are
							   # "kitty-corner" from each other count
							   # as neighbors.

# Tell POVME how to perform the calculations.
NumProcessors               1                              # POVME can use multiple processors on
                                                           # Unix-based systems.


# Tell POVME how to save the output
OutputFilenamePrefix          ./cutoff5/pointed_   # All the files POVME outputs will start
                                                           # with this prefix. POVME automatically
							   # creates any required directory
							   # (./POVME_test_run/ in this case).

CompressOutput                false                        # If you're short on disk space, POVME
                                                           # can automatically compress all output
							   # files using gz compression.
